### ISSUE TITLE
[BUG] no pictures after language change

### ISSUE THREAD

**Issue by akrajna** [vuestorefront/shopware-pwa#1129] opened 2020-09-23 08:01 UTC
### Describe the bug
There are no pictures after language change 

Actual behavior: not all pictures are displayed after changing the language: 
<img width="692" alt="LanguageChange" src="https://user-images.githubusercontent.com/57936972/93983991-8c067d00-fd83-11ea-9234-41ef80eb9f15.png">
Expected behavior: all pictures all displayed after changing the language 

Steps to reproduce:
1. go to the home page
2. click on language icon in the header
3. choose German language
4. see the error

**Comment by patzick** [comment] 2021-04-19 19:31
cannot reproduce any longer, closing

**Closed by patzick** 2021-04-19 19:31 UTC
Labels: bug, configuration
