### ISSUE TITLE
[BUG] Response of newsletter API-requests not returned

### ISSUE THREAD

**Issue by niklaswolf** [vuestorefront/shopware-pwa#1609] opened 2021-08-02 08:09 UTC
### Project type
- [x] Project (generated by CLI)
- [ ] Contribution (cloned/forked from GH)

### Describe the bug
The API-Response from the newsletter-endpoints is not returned. Like this there is no possibility to detect failed requests etc.

Example: 
https://github.com/vuestorefront/shopware-pwa/blob/master/packages/shopware-6-client/src/services/formsService.ts#L53

**Comment by patzick** [comment] 2021-08-31 13:37
Hey @niklas-wolf 
the API response with the successful request is 204.
When the request failed then the error is thrown so we have it in the try/catch block.
![image](https://user-images.githubusercontent.com/13100280/131512071-3de3cf62-91b0-4769-82e9-d50b46b01778.png)

Do you have something else in this endpoint response?

**Comment by niklaswolf** [comment] 2021-09-03 15:06
@patzick  yeah, the API returns something, but the methods from shopware-6-client do not return the response or the promise. Like this you're not able to react on the response when using those methods :) 
Example: https://github.com/vuestorefront/shopware-pwa/blob/master/packages/shopware-6-client/src/services/formsService.ts#L53

**Comment by patzick** [comment] 2021-09-06 07:41
I tested this and if the request is fine, then nothing is coming back from the API (204-no content). Can you show me what is returned? I could see the body only on error, so there was no point passing `return` in the place you showed. Please elaborate more on that if you can :)

**Comment by niklaswolf** [comment] 2021-09-06 07:47
@patzick  if there is an error returned (I think the actual problem was if someone tries to register with an already registered email), this error is inaccessible from outside. It is never passed to the function caller, as the response is not returned.
Granted this is more of an improvement than a bug, but it'd be really helpful if someone wants to write additional error handling (e.g. showing a error message) and/or a customized newsletter registration form

**Comment by patzick** [comment] 2021-09-06 08:05
When the error is returned (status !== 2xx) then the exception is thrown.
So we have these cases:
1. success - 204 response, no return needed as no content here
2. error - look at the example here: https://github.com/vuestorefront/shopware-pwa/blob/master/packages/default-theme/src/cms/elements/CmsElementNesletterForm.vue#L121 - still no return is necessary 

There is no case when we have status 200 and something in the response body, that's why this method is typed as `void`.
LMK what you think

**Comment by niklaswolf** [comment] 2021-09-06 08:19
@patzick I'm not quite sure about the fact, that if there is an error it results in a status !== 2xx. I think the status of the API-response still is 2xx, but the response contains an error-array.
If you're right and the status !== 2xx, then we can close this issue. Otherwise I think the response should be returned :)

**Comment by patzick** [comment] 2021-09-06 08:30
I agree, but couldn't reproduce that with 2xx response error (btw. then IMO API should be fixed to return non-2xx response). If you'll have this specific case please leave the reproduction in here. We'll reopen this issue and will take care of that :) thanks!

**Closed by patzick** 2021-09-06 08:30 UTC
Labels: bug, awaiting user response
