### ISSUE TITLE
[BUG] UNEXPECTED ERROR Error: FILE_ENDED

### ISSUE THREAD

**Issue by abvdveen** [vuestorefront/shopware-pwa#1198] opened 2020-10-22 10:57 UTC
Using npx @shopware-pwa/cli@canary init I get this error after answering 'y' to 'Do you want to allow dev mode for slots? (Don't use for production!) (y/N)'. This happens when I use my own Shopware 6.3.2.1 instance. I'm still able to launch the dev server after this.

Using https://pwa-demo-api.shopware.com as instance doesn't produce the error. So maybe it's related to the Shopware version and the demo uses an older version?

**Comment by mkucmus** [comment] 2020-10-26 09:36
@abvdveen I couldn't reproduce it TBH. Being on the same version of SW locally. 
Give us some more details related to your environment like: node version, npm, npx.

**Comment by abvdveen** [comment] 2020-10-26 09:48
@mkucmus: sure, versions:

node v15.0.1
npx/npm 7.0.3
yarn 1.22.5

I'm a novice in the nodejs/nuxt department. Perhaps you could give me some pointers on how to debug an error like this?

**Comment by mkucmus** [comment] 2020-12-02 12:24
> @mkucmus: sure, versions:
> 
> node v15.0.1
> npx/npm 7.0.3
> yarn 1.22.5
> 
> I'm a novice in the nodejs/nuxt department. Perhaps you could give me some pointers on how to debug an error like this?
the best way to debug such issues is having the project repository locally (not only the initiated one by cli) and follow the lines from the exception messages.

nevertheless, please set the node version to **v14.13.1** because it's the latest version we support, and it's a good time to run CLI again, because the `@canary` version was improved :+1: give some feedback after doing this :pray:

**Comment by patzick** [comment] 2021-04-29 12:19
This issue will be resolved with #1463

**Closed by patzick** 2021-04-29 12:19 UTC
Labels: bug, stability
