### ISSUE TITLE
[BUG] apiDefaults definition loses data in defaults

### ISSUE THREAD

**Issue by develth** [vuestorefront/shopware-pwa#1341] opened 2021-02-04 11:25 UTC
### Describe the bug
When adding e.g. this data into `shopware-pwa.config.js`, fields `media` and `name` is missing in request criteria:

**apiDefaults**

```
apiDefaults: {
  useCms: {
    limit: 12,
    includes: {
      product: ["unit", "productNumber", "purchaseUnit"],
      unit: ["id", "name", "shortCode"],
      product_media: ['position', 'media'],
    },
    associations: {
      properties:{
        associations: {
          media: {}
        }
      }
    }
  }
}
```

**composables / useCms / search - getDefaults:**

```
    product: [
      'unit',
      'productNumber',
      'purchaseUnit',
      'calculatedPrice',
      'calculatedPrices',
      'calculatedListingPrice',
      'cover',
      'parentId',
      'id',
      'translated',
      'optionIds',
      'properties',
      'manufacturer',
      'seoUrls',
      'crossSellings'
    ],
```

As soon as i remove the includes, `name` and `media` is back again.
When adding `name` and `media` to my includes, `calculatedPrice`and `calculatedPrices` is missing.

**Comment by niklaswolf** [comment] 2021-06-21 07:43
I run in this too. It seems kind of random, e.g. I added a new property to the includes array of products via the config file and the `name` property got lost as a result.

**Comment by patzick** [comment] 2021-06-21 08:05
By default, the merge is overriding the array if it's passed. This way you can also reduce fields you don't need which are fetched by default.
It's not a problem to change strategy to just add values but then we're cutting the possibility to override this and achieve smaller responses. This probably could be an additional flag in the settings file telling which strategy to use.
Would that work for you guys?

 Leaving for the implementation details:
we need to use `mergeWith` (like in `extendNuxtConfig.ts` file) and move the customizer to the commons package.

**Comment by SimonMarx** [comment] 2021-06-21 08:06
Had the same issue and got some informations:

The configuration of the `defaultApiParams.json` will get merged with the options configured in your `shopware-pwa.config.js` by lodashs merge function.

I checked how lodash merge handles deepmerge

Here is my example code:
```
const systemDefaults = {
  product: {
    aProp: 'foo',
    includes: ['name', 'anotherProp']
  }
}

const pwaConfigDefaults = {
  product: {
    bProb: 'faa',
    includes: ['myCustomInclude'],
  }
}

result = _.merge(systemDefaults, pwaConfigDefaults);
```

Getting as result:

```
{
   "product": {
      "aProp": "foo",
      "includes": [
         "myCustomInclude",
         "anotherProp"
      ],
      "bProb": "faa"
   }
}
```

If you take a look in the result the `includes` property (which contains a list/array) has the `name` entry missing, that happens because lodash handles arrays as objects (not confirmed, only a guess) and uses the array keys (0, 1, 2 and so on) to replace ("merge" :p) two lists by they keys.

Two more test scenarios with lodash:

**Merge 2 Lists directly**
```
const list1 = ['some', 'values'];
const list2 = ['another', 'list'];

result = _.merge(list1, list2);
```

**Result**
```
[
   "another",
   "list"
]
```


** Merge a list and an object which contains keys **
```
const list1 = ['some', 'values'];
const list2 = {5: 'another', 7: 'list'};

result = _.merge(list1, list2);
```

**Result:**
``` 
[
   "some",
   "values",
   null,
   null,
   null,
   "another",
   null,
   "list"
]
```

As you can see, lodash also fills empty "keys" (2, 3, 4 and 6) because they are not set in one of our lists we want to merge.

**Comment by patzick** [comment] 2021-06-21 09:12
Let's discuss the API in #1570 RFC :)

**Closed** 2021-07-27 15:11 UTC
Labels: bug
