### ISSUE TITLE
[BUG] Website is not starting from the top.

### ISSUE THREAD

**Issue by lbebnowicz** [vuestorefront/shopware-pwa#1429] opened 2021-04-15 07:17 UTC
### Describe the bug
Website is not starting from the top.

F.ex. if I click on product on HomePage, productPage is opening in the same place, as homePage was. If i was on the end of home page, next website will open on the end

### Additional context
Shopware v6.3.5.1 Stable Version
Shopware PWA 0.7.1

**Comment by patzick** [comment] 2021-04-26 13:43
Hey @lbebnowicz 
I cannot reproduce this problem on our demo instance
https://shopware-pwa.storefrontcloud.io/

https://user-images.githubusercontent.com/13100280/116092300-f975e580-a6a5-11eb-9f9b-413be4eac4d6.mp4

Please provide reproduction steps so we can do something about it :)

**Comment by mkucmus** [comment] 2021-05-11 13:26
I'm closing an issue due to no activity.

**Comment by patzick** [comment] 2021-08-31 14:59
closing, this is most likely an error inside the implementation

**Closed by patzick** 2021-08-31 14:59 UTC
Labels: bug, awaiting user response
